version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/elixir:1.8
      - image: circleci/postgres:9.4.12
    working_directory: ~/parear
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/parear

  retrieve_dependencies:
    docker:
      - image: circleci/elixir:1.8
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/parear
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: pwd && ls -la
      - run: cd repository  && mix deps.get && cd -
      - run: cd parear      && mix deps.get && cd -
      - run: cd pair_stairs && mix deps.get && cd -

workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_code
      - retrieve_dependencies:
          requires:
            - checkout_code
