version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/elixir:1.8
    working_directory: ~/parear
    steps:
      - checkout
      - save_cache:
          key: v1-repo-code-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/parear

  retrieve_dependencies:
    docker:
      - image: circleci/elixir:1.8
    working_directory: ~/parear
    steps:
      - restore_cache:
          key: v1-repo-code-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get
      - save_cache:
          key: v1-repo-deps-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/parear

  run_tests:
    docker:
      - image: circleci/elixir:1.8
      - image: circleci/postgres:9.4.12
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    working_directory: ~/parear
    steps:
      - restore_cache:
          key: v1-repo-deps-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - run: mix do ecto.create, ecto.migrate
      - run: make unit-test

workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_code
      - retrieve_dependencies:
          requires:
            - checkout_code
