- hosts: "{{ server_name }}"
  roles:
   - geerlingguy.swap
   - dokku_bot.ansible_dokku

  vars:
    swap_file_size_mb: '2048'
    dokku_version: 0.24.9
    dokku_users:
      - name: Vitor Cavalcanti
        username: vrcca
        ssh_key: "{{lookup('file', '~/.ssh/id_rsa.pub')}}"
    dokku_plugins:
      - name: clone
        url: https://github.com/crisward/dokku-clone.git
      - name: letsencrypt
        url: https://github.com/dokku/dokku-letsencrypt.git
      - name: postgres
        url: https://github.com/dokku/dokku-postgres.git

  tasks:
    - name: "Create 'parear' app"
      dokku_app:
        app: &appname parear
